### ISSUE TITLE
OK if we change master to main?

### ISSUE THREAD

**Issue by bast** [coderefinery/sphinx-lesson-template#5]
... and adapt the workflow? Just to be consistent with default branch naming on GitHub/GitLab.

I can do the change, just wanted to check whether you agree.

**Comment by rkdarst** [comment]
Yeah, that would be expected from a project now.  Also you can
do the same for the sphinx-lesson repo, these two are close mirrors of
each other.

There may be edits needed in the actions builder, and also probably in
the docs of sphinx-lesson about how things are converted.

**Comment by bast** [comment]
OK - I will take care of that and adjust both.

**Comment by robertodr** [comment]
There's one leftover use of `master` in `conf.py`, should that be changed to `main` or to some code to detect the name of the default branch?

**Comment by robertodr** [comment]
Renaming done!
